config/routes.rb
Rails.application.routes.draw do
  get 'home/me'

  resources :subscriptions

  resources :stories do
		member do
			post 'approve'
			post 'unapprove'
		end
	end

  resources :letters

  get '/subscribe', to: 'subscriptions#new', as: :subscribe
  get '/logout', to: 'sessions#destroy', as: :logout
  get '/login', to: 'sessions#new', as: :login
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/failure', to: 'sessions#login_error'
  get 'sessions/create'
  get 'sessions/new'
  get 'home', to: 'home#index',  as: :home
  get 'me', to: 'home#me',  as: :me

  post '/email_processor' => 'griddler/emails#create'
  root 'home#index'

end

app/models/email_processor.rb
class EmailProcessor

  def initialize(email)
    @email = email
  end

  def process
    if subscribe_message?
      create_new_subscription
    elsif unsubscribe_message?
      remove_subscription
    else
      create_new_story
    end
  end

  private

  def subscribe_message?
    @email.body =~ /^subscribe/
  end

  def create_new_subscription
    existing = Subscription.where(email: @email.from).first
    if existing.nil?
      Subscription.create(email:@email.from)
      Notification.welcome(@email.from)
    end
  end

  def unsubscribe_message?
    @email.body =~ /^unsubscribe/
  end

  def remove_subscription
    Subscription.where(email: @email.from).delete_all
  end

  def create_new_story

    story = Story.new(from: @email.from,
              title: @email.subject,
              text: @email.body)

    user = User.from_email(@email.from)

    story.user = user if user.present?
  end
end

app/models/letter.rb
class Letter < ActiveRecord::Base
end

app/models/story.rb
class Story < ActiveRecord::Base
  belongs_to :user
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  def user?
    User.where(email: email).count > 0
  end
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :stories

  def subscribed?
    sub = Subscription.where(email: email).count > 0
  end

  def admin?
    email == 'chrisortman@gmail.com'
  end

  class << self
    
    def login_from_facebook(auth_hash)
      facebook_id = auth_hash[:uid]

      user = User.where(facebook_id: facebook_id).first

      if user.nil?
        user = User.create!(facebook_id: facebook_id.to_s)
      end

      user.name  = auth_hash[:info][:name]
      user.email = auth_hash[:info][:email]
      user.save!

      user
    end

    def from_email(email)
      where(email: email).first
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :logged_in?, :current_user

  protected

  def must_be_logged_in
    if ! logged_in? || current_user.nil?
      redirect_to login_url
    end
  end

  def must_be_admin
    if logged_in? && current_user.present?
      if ! current_user.admin?
        render :nothing, :status => 404
      end
    end
  end

  def logged_in?
    session[:user_id].present?
  end

  def current_user
    @current_user ||= User.find(session[:user_id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @subscriber_count = Subscription.count
    @story_count = Story.count
    @letter_count = Letter.count

  end

  def me

  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.login_from_facebook(auth_hash)
    session[:user_id] = user.id

    # Currently using the Facebook JS method to login
    # so we return true, and in our session/new view
    # we decide where we are redirecting to
    respond_to do |format|
      format.html { redirect_to me_url}
      format.js { render :js => "true" }
    end

  end

  def destroy
    session[:user_id] = nil
    redirect_to home_url
  end

  def login_error
    render :text => "Sorry"
  end

  protected
  
  def auth_hash
    request.env['omniauth.auth']
  end

end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_action :must_be_logged_in
  before_action :set_story, only: [:show, :edit, :update, :destroy,:approve,:unapprove]
  before_action :must_be_admin, only: [:approve,:unapprove]

  # GET /stories
  # GET /stories.json
  def index
    @stories = current_user.stories
  end

  # GET /stories/1
  # GET /stories/1.json
  def show
  end

  # GET /stories/new
  def new
    @story = Story.new
  end

  # GET /stories/1/edit
  def edit
  end

  # POST /stories
  # POST /stories.json
  def create
    @story = Story.new(story_params)

    @story.user = current_user

    respond_to do |format|
      if @story.save
        format.html { redirect_to @story, notice: 'Story was successfully created.' }
        format.json { render :show, status: :created, location: @story }
      else
        format.html { render :new }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stories/1
  # PATCH/PUT /stories/1.json
  def update
    respond_to do |format|
      if @story.update(story_params)
        format.html { redirect_to @story, notice: 'Story was successfully updated.' }
        format.json { render :show, status: :ok, location: @story }
      else
        format.html { render :edit }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stories/1
  # DELETE /stories/1.json
  def destroy
    @story.destroy
    respond_to do |format|
      format.html { redirect_to stories_url, notice: 'Story was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def approve
    @story.approved = true
    @story.save!

    respond_to do |format|
      format.html { redirect_to @story, notice: 'Story approved' }
    end
  end

  def unapprove
    @story.approved = false
    @story.save!
    respond_to do |format|
      format.html { redirect_to @story, notice: 'Story unapproved' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_story
      @story = Story.find(params[:id])

      if @story.user != current_user
        @story = nil
        render :nothing, :status => 401
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def story_params
      params.require(:story).permit(:from, :text, :user_id, :title)
    end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_filter :must_be_logged_in, :must_be_admin, :only => [:index]

  def index
    @subscriptions = Subscription.all
  end

  def new
    @subscription = Subscription.new
  end

  def create

    sub = Subscription.where(email: subscription_params[:email])

    if sub.size == 0
      sub = Subscription.create(subscription_params)
    end
    
  end

  protected

  def current_user_is_subscribing?
    logged_in? && subscription_params[:email] == current_user.email
  end

  def subscription_params
    params.require(:subscription).permit(:email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def yes_no(x)
    x ? "Yes" : "No"
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/stories_helper.rb
module StoriesHelper

	@@md = Redcarpet::Markdown.new(
		Redcarpet::Render::HTML.new(
			no_links: true,
			hard_wrap: true
	))
	
	def markdown(text)
		@@md.render(text).html_safe
	end
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/home/index.html.erb
<h2><%= @subscriber_count %> subscribers </h2>

<h2><%= @story_count %> stories </h2>

<h2><%= @letter_count %> letters </h2>

<% if logged_in? && current_user.subscribed? %>
  <%= current_user.email %>  is subscribed to our emails
<% elsif logged_in? %>
  <%= form_for Subscription.new(email: current_user.email) do |f| %>
    <%= f.hidden_field :email %>
    <button type="submit" class="btn btn-lg btn-success">Subscribe <%= current_user.email %></button>
  <% end %>
<% else %>
  <%= link_to 'Subscribe', subscribe_path, class: 'btn btn-lg btn-success' %>
<% end %>

app/views/home/me.html.erb
<p>
<% if current_user.subscribed? %>
  <%= current_user.email %>  is subscribed 
<% else %>
  <%= form_for Subscription.new(email: current_user.email) do |f| %>
    <%= f.hidden_field :email %>
    <button type="submit" class="btn btn-lg btn-success">Subscribe <%= current_user.email %></button>
  <% end %>
<% end %>

</p>

<ul>
<% current_user.stories.each do |s| %>
  <li><%= link_to s.title, s %></li>
<% end %>
</ul>

<p>
<%= link_to 'Add new story', new_story_path %>
</p>

<% if current_user.admin? %>
  <p>
  <%= link_to 'Prepare letter', stories_path %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AngelTree</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="container">
    <div class="col-md-offset-8 col-md-4">
      <% if logged_in? %>
        <%= link_to current_user.name, me_url %> | <%= link_to "Sign Out", logout_url %>
      <% else %>
        <%= link_to "Sign In | Create Account", login_url %>
      <% end %>
    </div>
  </div>
  <div class="container">
    <%= yield %>
  </div>

</body>
</html>

app/views/notification/new_letter.html.erb
<h1>Notification#new_letter</h1>

<p>
  <%= @greeting %>, find me in app/views/notification/new_letter.html.erb
</p>

app/views/notification/new_letter.text.erb
<%= @letter.text %>

app/views/notification/welcome.html.erb
Hi

app/views/stories/_form.html.erb
<%= form_for(@story) do |f| %>
  <% if @story.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@story.errors.count, "error") %> prohibited this story from being saved:</h2>

      <ul>
      <% @story.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :text %><br>
    <%= f.text_area :text, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :from %><br>
    <%= f.text_field :from, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= label_tag :user_email %><br>
    <%= text_field_tag :user_email,nil, class: 'form-control' %>
  </div>
  <div class="field">
  </div>
  <div class="actions">
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/stories/edit.html.erb
<h1>Editing Story</h1>

<%= render 'form' %>

<%= link_to 'Show', @story %> |
<%= link_to 'Back', stories_path %>

app/views/stories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Stories</h1>

<table class="table">
  <thead>
    <tr>
      <th>From</th>
      <th>User</th>
      <th>Title</th>
      <th>Text</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stories.each do |story| %>
      <tr>
        <td><%= story.from %></td>
        <td><%= story.user_id %></td>
        <td><%= story.title %></td>
        <td><%= story.text %></td>
        <td><%= link_to 'Show', story %></td>
        <td><%= link_to 'Edit', edit_story_path(story) %></td>
        <td><%= link_to 'Destroy', story, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Story', new_story_path %>

app/views/stories/new.html.erb
<h1>New Story</h1>

<%= render 'form' %>

<%= link_to 'Back', stories_path %>

app/views/stories/show.html.erb
<p id="notice"><%= notice %></p>

<div class="page-header">
  <h2><%= @story.title %> from <%= @story.from %></h2>
</div>

<%= markdown(@story.text) %>

<hr>

<p>
<% if @story.approved? %>
  Story approved. <%= button_to "Unapprove", {action: 'unapprove'}, class: 'btn btn-danger' %>
<% else %>
  <%= button_to "Approve", {action: 'approve'}, class: 'btn btn-success' %>
<% end %>
<%= link_to 'Edit', edit_story_path(@story) %> |
<%= link_to 'Back', stories_path %>
</p>

app/views/subscriptions/create.html.erb
<h1> Thank you!  </h1>

<p>
  You should get your next email sometime this week.
</p>

<p>
  If you'd like to share a story of your own simply email it to 
  <a href="mailto:letters@inbound.chrisortman.com">letters@inbound.chrisortman.com</a>
</p>

<p>
  <%= link_to "Home", home_path %>
</p>

app/views/subscriptions/index.html.erb
<table class="table">
  <thead>
    <tr>
      <th>Email</th>
      <th>Created</th>
      <th>User</th>
    </tr>
  </thead>
  <tbody>
  <% @subscriptions.each do |s| %>
    <tr>
      <td>
        <%= s.email %>
      </td>
      <td>
        <%= s.created_at %> 
      </td>
      <td>
        <%= yes_no(s.user?) %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/subscriptions/new.html.erb
<p class="lead">
Subscribe today to get stories from other christians about how they have
witnessed God's work in our daily lives
</p>

<%= form_for @subscription, html: {class: 'form-inline'} do |f| %>

  <div class="form-group">
    <%= f.label :email %>
    <%= f.text_field :email, class: 'form-control', placeholder: 'you@example.com' %>
  </div>

  <%= f.submit 'Subscribe', class: 'btn btn-primary' %>
<% end %>